package dev.rodrigosambade.jdbc;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public final class JdbcExercises {

    private static final String DATABASE_URL =
            "jdbc:h2:mem:jdbc_exercises;DB_CLOSE_DELAY=-1";

    private JdbcExercises() {
    }

    public static Connection open() throws SQLException {
        return DriverManager.getConnection(DATABASE_URL, "sa", "");
    }

    public static void createSchema(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS producto (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR(120) UNIQUE NOT NULL,
                        precio DECIMAL(12,2) NOT NULL,
                        stock INT NOT NULL
                    )
                    """);
        }
    }

    public static int insert(
            Connection connection,
            String name,
            BigDecimal price,
            int stock) throws SQLException {
        String sql = "INSERT INTO producto(nombre, precio, stock) VALUES (?, ?, ?)";

        try (PreparedStatement statement = connection.prepareStatement(
                sql,
                Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, name);
            statement.setBigDecimal(2, price);
            statement.setInt(3, stock);
            statement.executeUpdate();

            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (!generatedKeys.next()) {
                    throw new SQLException("No se obtuvo la clave del producto");
                }
                return generatedKeys.getInt(1);
            }
        }
    }

    public static List<String> namesUnder(
            Connection connection,
            BigDecimal maximumPrice) throws SQLException {
        String sql = "SELECT nombre FROM producto WHERE precio < ? ORDER BY nombre";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setBigDecimal(1, maximumPrice);

            try (ResultSet resultSet = statement.executeQuery()) {
                List<String> names = new ArrayList<>();
                while (resultSet.next()) {
                    names.add(resultSet.getString("nombre"));
                }
                return List.copyOf(names);
            }
        }
    }

    public static BigDecimal inventoryValue(Connection connection) throws SQLException {
        String sql = "SELECT COALESCE(SUM(precio * stock), 0) FROM producto";

        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            resultSet.next();
            return resultSet.getBigDecimal(1);
        }
    }

    public static List<String> columns(Connection connection) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();

        try (ResultSet resultSet = metadata.getColumns(
                null,
                null,
                "PRODUCTO",
                null)) {
            List<String> columns = new ArrayList<>();
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME"));
            }
            return List.copyOf(columns);
        }
    }

    public static void batchRestock(
            Connection connection,
            Map<Integer, Integer> unitsByProduct) throws SQLException {
        String sql = "UPDATE producto SET stock = stock + ? WHERE id = ?";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            for (Map.Entry<Integer, Integer> entry : unitsByProduct.entrySet()) {
                statement.setInt(1, entry.getValue());
                statement.setInt(2, entry.getKey());
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }

    public static void main(String[] args) throws Exception {
        try (Connection connection = open()) {
            createSchema(connection);

            int keyboardId = insert(
                    connection,
                    "Teclado",
                    new BigDecimal("35.90"),
                    4);
            insert(
                    connection,
                    "Ratón",
                    new BigDecimal("20.50"),
                    10);

            System.out.println(namesUnder(connection, new BigDecimal("30")));
            batchRestock(connection, Map.of(keyboardId, 3));
            System.out.println("Valor inventario: " + inventoryValue(connection));
            System.out.println("Columnas: " + columns(connection));
        }
    }
}
