package dev.rodrigosambade.jdbc;
import java.sql.*;
import java.math.BigDecimal;
import java.util.*;
public final class JdbcExercises {
    public static Connection open() throws SQLException {
        return DriverManager.getConnection("jdbc:h2:mem:jdbc_exercises;DB_CLOSE_DELAY=-1","sa","");
    }
    public static void createSchema(Connection c)throws SQLException{
        try(var s=c.createStatement()){
            s.execute("create table if not exists producto(id int generated by default as identity primary key,nombre varchar(120) unique not null,precio decimal(12,2) not null,stock int not null)");
        }
    }
    public static int insert(Connection c,String name,BigDecimal price,int stock)throws SQLException{
        try(var ps=c.prepareStatement("insert into producto(nombre,precio,stock) values(?,?,?)",Statement.RETURN_GENERATED_KEYS)){
            ps.setString(1,name);
            ps.setBigDecimal(2,price);
            ps.setInt(3,stock);
            ps.executeUpdate();
            try(var rs=ps.getGeneratedKeys()){
                rs.next();
                return rs.getInt(1);
            }
        }
    }
    public static List<String> namesUnder(Connection c,BigDecimal max)throws SQLException{
        try(var ps=c.prepareStatement("select nombre from producto where precio<? order by nombre")){
            ps.setBigDecimal(1,max);
            try(var rs=ps.executeQuery()){
                List<String>x=new ArrayList<>();
                while(rs.next())x.add(rs.getString(1));
                return List.copyOf(x);
            }
        }
    }
    public static BigDecimal inventoryValue(Connection c)throws SQLException{
        try(var ps=c.prepareStatement("select coalesce(sum(precio*stock),0) from producto");
        var rs=ps.executeQuery()){
            rs.next();
            return rs.getBigDecimal(1);
        }
    }
    public static List<String> columns(Connection c)throws SQLException{
        DatabaseMetaData md=c.getMetaData();
        try(var rs=md.getColumns(null,null,"PRODUCTO",null)){
            List<String>x=new ArrayList<>();
            while(rs.next())x.add(rs.getString("COLUMN_NAME"));
            return List.copyOf(x);
        }
    }
    public static void batchRestock(Connection c,Map<Integer,Integer> units)throws SQLException{
        try(var ps=c.prepareStatement("update producto set stock=stock+? where id=?")){
            for(var e:units.entrySet()){
                ps.setInt(1,e.getValue());
                ps.setInt(2,e.getKey());
                ps.addBatch();
            }
            ps.executeBatch();
        }
    }
    public static void main(String[]args)throws Exception{
        try(var c=open()){
            createSchema(c);
            int a=insert(c,"Teclado",new BigDecimal("35.90"),4);
            insert(c,"Ratón",new BigDecimal("20.50"),10);
            System.out.println(namesUnder(c,new BigDecimal("30")));
            batchRestock(c,Map.of(a,3));
            System.out.println("Valor inventario: "+inventoryValue(c));
            System.out.println("Columnas: "+columns(c));
        }
    }
}
